title: The All-weather MUse Supernova Integral field Nearby Galaxies (AMUSING) survey
description: > # this means to ignore newlines until "baseurl:" abans: Revolutionizing supernova environments and galaxy formation, enrichment, and evolution with IFS
  Funded by the European Union's Horizon 2020 research and innovation programme under the Marie Skłodowska-Curie grant agreement No. 839090.

theme: minima
markdown: kramdown
github_username:  amusing-muse

exclude:
  - Gemfile
  - Gemfile.lock

header_pages:
  - survey.md
  - reduction.md
  - sample.md
  - people.md
  - publications.md
  - projects.md
  - other.md
