title: The All-weather MUse Supernova Integral field Nearby Galaxies (AMUSING) survey
description: > # this means to ignore newlines until "baseurl:"
  The All-weather MUse Supernova Integral field Nearby Galaxies (AMUSING) survey

theme: minima
markdown: kramdown
github_username:  amusing-muse

exclude:
  - Gemfile
  - Gemfile.lock
