title: The AMUSING survey
description: > # this means to ignore newlines until "baseurl:"
  The All-weather MUse Supernova Integral field Nearby Galaxies (AMUSING) survey

theme: minima
twitter_username: lgalbany
github_username:  lgalbany

exclude:
  - Gemfile
  - Gemfile.lock

header_pages:
 - People.md
 - Characterization.md
 - Publications.md
