title: The AMUSING survey
description: > # this means to ignore newlines until "baseurl:"
  The All-weather MUse Supernova Integral-field Nearby Galaxies survey

theme: minima

exclude:
  - Gemfile
  - Gemfile.lock

header_pages:
 - People.md
 - Characterization.md
 - Publications.md
