title: The AMUSING survey
description: > # this means to ignore newlines until "baseurl:"
  The All-weather MUse Supernova Integral field Nearby Galaxies (AMUSING) survey

theme: minima
markdown: kramdown
twitter_username: lgalbany
github_username:  lgalbany

exclude:
  - Gemfile
  - Gemfile.lock

header_pages:
 - people.md
 - Characterization.md
 - publications.md
